service: wechirka-server-v1
frameworkVersion: '3'
useDotenv: true
plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 512
  stage: dev
  timeout: 15
  region: eu-central-1
  environment:
    SECRET_KEY: ${env:SECRET_KEY}
    ACCESS_KEY_ID: ${env:ACCESS_KEY_ID}
    SECRET_ACCESS_KEY: ${env:SECRET_ACCESS_KEY}
    REGION: ${env:REGION}
    GOOGLE_CLIENT_SECRET: ${env:GOOGLE_CLIENT_SECRET}
    GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID}
    GOOGLE_CALLBACK_URL: ${env:GOOGLE_CALLBACK_URL}
    FACEBOOK_ID: ${env:FACEBOOK_ID}
    FACEBOOK_SECRET: ${env:FACEBOOK_SECRET}
    FACEBOOK_CALLBACK_URL: ${env:FACEBOOK_CALLBACK_URL}
    BOT_TELEGRAM: ${env:BOT_TELEGRAM}
    BOT_VIBER: ${env:BOT_VIBER}
    FRONT_LINK: ${env:FRONT_LINK}
    BACK_LINK: ${env:BACK_LINK}
    VIBER_ACCESS_TOKEN: ${env:VIBER_ACCESS_TOKEN}
    CLOUDINARY_CLOUD_NAME: ${env:CLOUDINARY_CLOUD_NAME}
    CLOUDINARY_API_KEY: ${env:CLOUDINARY_API_KEY}
    CLOUDINARY_API_SECRET: ${env:CLOUDINARY_API_SECRET}
    AVATAR: ${env:AVATAR}
    MASTER: ${env:MASTER}
    NOREPLY_MAIL: ${env:NOREPLY_MAIL}
    NOREPLY_PASSWORD: ${env:NOREPLY_PASSWORD}
    NGROK_AUTHTOKEN: ${env:NGROK_AUTHTOKEN}
    CODE_LINK: ${env:CODE_LINK}
    VIBER_AVATAR: ${env:VIBER_AVATAR}

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
